name: Hello world Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: find $(pwd)
        shell: bash


  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: find $(pwd)
        shell: bash