name: OpenAPI Client Generate

on:
  pull_request:
    branches:
      - main
    types:
      - "closed"
    paths:
      - 'spec.yml'
  

jobs:
  generate-code:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout Client Respository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CLIENT_TOKEN }}
        repository: fujisw/github-actions-example-openapi-client-repository
        path: tmp
        
    - name: Generate code
      uses: docker://openapitools/openapi-generator-cli
      with:
        args: generate -g typescript-axios -i openapi/spec.yml -o ./tmp/__generated__

    - name: Show output
      run: ls -la ./tmp/__generated__
    
    - name: Grant file permissions to prevent error on `Create Pull Request` step
      run: sudo chown -R $USER:$USER .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.14.0
      with:
        token: ${{ secrets.CLIENT_TOKEN}}
        path: tmp
        commit-message: auto generated from ${{ github.event.pull_request.html_url }}
        title: ${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.html_url }}
        branch: feature/codegen
        branch-suffix: short-commit-hash
