name: OpenAPI Client Generate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - "closed"
    paths:
      - 'openapi/spec.yml'
  

jobs:
  generate-code:
    if: |
      github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout Client Respository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CLIENT_TOKEN }}
        repository: fujisw/github-actions-example-openapi-client-repository
        path: tmp
        
    - name: Generate code
      uses: docker://openapitools/openapi-generator-cli
      with:
        args: generate -g typescript-axios -i openapi/spec.yml -o ./tmp/__generated__

    - name: Grant file permissions to prevent error on `Create Pull Request` step
      run: sudo chown -R $USER:$USER .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.14.0
      with:
        token: ${{ secrets.CLIENT_TOKEN }}
        path: tmp
        commit-message: auto generated from ${{ github.event.pull_request.html_url }}
        title: _ ${{ github.event.pull_request.title }}
        branch: feature/codegen
        branch-suffix: short-commit-hash
